FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py wait_for_db && python manage.py migrate && python manage.py collectstatic --noinput && (python manage.py load_ingredients || true) && (python manage.py seed_demo || true) && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"]

